# Generated by Django 4.2 on 2023-09-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.CharField(max_length=2)),
                ('fechaNac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=35)),
                ('lugarNac', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cedula_prov', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rif', models.CharField(max_length=30)),
                ('nombre_prov', models.CharField(max_length=35)),
                ('apellido_prov', models.CharField(max_length=35)),
                ('direccion_prov', models.CharField(max_length=35)),
                ('telefono_prov', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombrep', models.CharField(max_length=35)),
                ('cantidad', models.CharField(max_length=35)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id_examenes', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_examen', models.CharField(max_length=35)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pacientes.pacientes')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pacientes.productos')),
            ],
        ),
    ]
