# Generated by Django 4.2 on 2023-06-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=35)),
                ('nombrep', models.CharField(max_length=35)),
                ('cantidad', models.CharField(max_length=100)),
            ],
        ),
    ]
