# Generated by Django 4.2 on 2023-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0002_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('ciudad', models.CharField(max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
